### ISSUE TITLE
Add custom domain name to api gateway

### ISSUE THREAD

**Issue by DeusFerrariis** [DeusFerrariis/rust-todo-infra#1]
# Tasks

- [ ] Fetch agoristdigital domain
- [ ] Create ACM Cert for Domain
- [ ] Create custom domain for api gateway
- [ ] Link dns record to api gateway
- [ ] Route <custom domain>/app to web 
- [ ] Route <custom domain>/api to api
